server:
  port: 9090
spring:
  r2dbc:
    url: r2dbc:h2:file:///~/db/testdb
    password: test
    username: sa
    pool:
      enabled: true
  datasource:
    driver-class-name: h2
  h2:
    console:
      enabled: true
      path: /h2-console