---
apiVersion: v1
kind: Service
metadata:
  name: counter-svc
spec:
  type: LoadBalancer
  selector:
    app: visit-counter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reddis-db-svc
spec:
  type: LoadBalancer
  selector:
    app: reddis-db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379